all: ex1ClienteTcp.out ex1ServidorTcp.out

ex1ClienteTcp.out: clienteTcp.c
	gcc -std=c11 -Wall -Wextra -o ex1ClienteTcp.out clienteTcp.c
	
ex1ServidorTcp.out: servidorTcp.c
	gcc -std=c11 -Wall -Wextra -o ex1ServidorTcp.out servidorTcp.c